-- The schema as it was before migrations existed. IF NOT EXISTS lets an existing
-- database be adopted without changes.
CREATE TABLE IF NOT EXISTS events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    token       TEXT NOT NULL UNIQUE,
    is_open     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS photos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    original_name  TEXT NOT NULL,
    file_name      TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'processing', 'done', 'error')),
    error          TEXT,
    face_count     INTEGER NOT NULL DEFAULT 0,
    processing_ms  INTEGER,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at   TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS faces (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    photo_id   BIGINT NOT NULL REFERENCES photos(id) ON DELETE CASCADE,
    event_id   BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    x INTEGER, y INTEGER, w INTEGER, h INTEGER,
    score      REAL,
    embedding  BYTEA NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_photos_event ON photos(event_id);
CREATE INDEX IF NOT EXISTS idx_faces_event ON faces(event_id);
CREATE INDEX IF NOT EXISTS idx_faces_photo ON faces(photo_id);
